GET http://localhost:8080/webapi/libros


#####
POST http://localhost:8080/webapi/libros
content-type:application/json


{
    "isbn": "1a",
    "titulo": "java web",
    "autor": "pedro",
    "paginas": 100

}
#####
DELETE  http://localhost:8080/webapi/libros/1a